### ISSUE TITLE
C:\Program Files 或者 C:\Program Files(86)  内的浏览器不兼容  系统自带IE11.0.95版本

### ISSUE THREAD

**Issue by RebornWXY** [jaywcjlove/translater.js#10]
有一个节点 找不到 浏览器不支持 Text的属性,换成标签 自带属性进行表示就行了.时间太长了,具体忘了.....

**Comment by jaywcjlove** [comment]
@RebornWXY 这种形式的不支持？

```html
<div>
  这里是中文
  <!--{jp}ここは日本語です-->
  <!--{en}Here is English-->
</div>
```

**Comment by RebornWXY** [comment]
我刚刚又测试了一下 你可以看一下截图 .可以改变 filter 类型 进行控制这个错误.

![image](https://user-images.githubusercontent.com/33017030/49003621-3ec41f00-f19d-11e8-9424-29020c5909ad.png)

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/translater.js/blob/b5fb0d0c5040caf5e6cbf8754c526f722175a5cc/dist/translater.js#L236-L240

看上去是这个地方不兼容IE，回头我找个机子调试一下。

**Comment by RebornWXY** [comment]
> [translater.js/dist/translater.js](https://github.com/jaywcjlove/translater.js/blob/b5fb0d0c5040caf5e6cbf8754c526f722175a5cc/dist/translater.js#L236-L240)
> 
> Lines 236 to 240 in [b5fb0d0](/jaywcjlove/translater.js/commit/b5fb0d0c5040caf5e6cbf8754c526f722175a5cc)
> 
>  while (o = s.nextNode()) { 
>      if (o.parentElement.tagName !== "SCRIPT" && o.parentElement.tagName !== "STYLE" && o.parentElement.tagName !== "CODE" && trim(o.nodeValue) !== "") { 
>          r.push(o); 
>      } 
>  } 
> 看上去是这个地方不兼容IE，回头我找个机子调试一下。

所有的window 都这样 只要是用那个老的ie .... 不是个小问题啊 要重视 真的
